//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarKuz.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int IdCheque { get; set; }
        public Nullable<int> IdReception { get; set; }
        public Nullable<int> IdService { get; set; }
    
        public virtual Reception Reception { get; set; }
        public virtual Service Service { get; set; }
    }
}
