//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarKuz.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicView
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string NameSpecialization { get; set; }
        public string Number { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int IdGraphic { get; set; }
        public int IdCabinet { get; set; }
        public int IdUser { get; set; }
        public int Expr1 { get; set; }
        public int IdRole { get; set; }
        public int Expr2 { get; set; }
        public int IdSpecialization { get; set; }
    }
}
