//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarKuz.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCard
    {
        public int IdCard { get; set; }
        public int IdPet { get; set; }
        public Nullable<int> IdDiagnosis { get; set; }
        public int IdReception { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual Reception Reception { get; set; }
        public virtual Status Status { get; set; }
    }
}
