//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarKuz.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reception()
        {
            this.Cheque = new HashSet<Cheque>();
            this.MedicalCard = new HashSet<MedicalCard>();
        }
    
        public int IdReception { get; set; }
        public int IdUser { get; set; }
        public int IdPet { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Appointment { get; set; }
        public bool IsArchive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalCard> MedicalCard { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual User User { get; set; }
    }
}
